# Generated by Django 3.2.4 on 2021-06-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_child_milestone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
